import Footer from "./components/footer/footer"
import Navbar from "./components/navbar/navbar"
import "./global.css"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="container">
        <Navbar />
        {children}
        <Footer />
        </div>
      </body>
    </html>
  )
}
